version: "3"

services:
  postgres:
    env_file:
      - ../.env
    container_name: omnistack-saas-postgres
    image: postgres:11.7-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # redis:
  #   container_name: omnistack-saas-redis
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  # mongo:
  #   container_name: omnistack-saas-mongo
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  # mailhog:
  #   container_name: omnistack-saas-mailhog
  #   image: mailhog/mailhog
  #   ports:
  #     - "8025:8025"
  #     - "1025:1025"

volumes:
  postgres_data:
